=== Alfresco/acs-event-model/src/main/resources/json-schema/auditRecordResourceTransactionEvent.json
{
  "$schema": "https://json-schema.org/draft/2019-09/schema",
  "type": "object",
  "properties": {
    "specversion": { "type": "string" },
    "type": { "type": "string" },
    "id": { "type": "string" },
    "source": { "type": ["string", "null"] },
    "time": { "type": "string", "format": "date-time" },
    "dataschema": { "type": "string" },
    "datacontenttype": { "type": "string" },
    "data": {
      "type": "object",
      "properties": {
        "eventGroupId": { "type": ["string", "null"] },
        "resource": {
          "type": "object",
          "properties": {
            "@type": { "type": "string" },
            "auditApplicationId": { "type": "string" },
            "auditData": {
              "type": "object",
              "properties": {
                "transaction": {
                  "type": "object",
                  "properties": {
                    "path": { "type": "string" },
                    "sub-actions": { "type": "string" },
                    "aspects": {
                      "type": "object",
                      "properties": {
                        "add": {
                          "type": "array",
                          "items": {
                            "type": "object",
                            "properties": {
                              "namespaceURI": { "type": "string" },
                              "localName": { "type": "string" },
                              "prefixString": { "type": "string" }
                            },
                            "required": ["namespaceURI", "localName", "prefixString"]
                          }
                        }
                      }
                    },
                    "action": { "type": "string" },
                    "type": { "type": "string" },
                    "user": { "type": "string" },
                    "properties": {
                      "type": "object",
                      "properties": {
                        "add": {
                          "type": "object",
                          "additionalProperties": true
                        }
                      }
                    }
                  },
                  "required": ["path", "sub-actions", "aspects", "action", "type", "user", "properties"]
                }
              },
              "required": ["transaction"]
            }
          },
          "required": ["@type", "auditApplicationId", "auditData"]
        }
      },
      "required": ["eventGroupId", "resource"]
    }
  },
  "required": ["specversion", "type", "id", "source", "time", "dataschema", "datacontenttype", "data"]
}

=== Alfresco/acs-event-model/src/test/resources/AuditRecordResource.json
{
  "specversion" : "1.0",
  "type" : "org.alfresco.event.audit.entryCreated",
  "id" : "47fbc01e-dc47-4f4e-9a60-710045a3d65a",
  "source" : null,
  "time" : "2025-07-09T10:26:25.105444+02:00",
  "dataschema" : "https://api.alfresco.com/schema/event/repo/v1/auditEntryCreated",
  "datacontenttype" : "application/json",
  "data" : {
    "eventGroupId" : null,
    "resource" : {
      "@type" : "AuditEntryResource",
      "auditApplicationId" : "TXN_READ_ONLY",
      "auditData" : {
        "transaction" : {
          "path" : "/app:company_home/st:sites/cm:surf-config/cm:components/cm:page.component-1-1.user~admin~dashboard.xml",
          "sub-actions" : "createNode updateNodeProperties addNodeAspect createContent",
          "aspects" : {
            "add" : [ {
              "namespaceURI" : "http://www.alfresco.org/model/content/1.0",
              "localName" : "indexControl",
              "prefixString" : "cm:indexControl"
            }, {
              "namespaceURI" : "http://www.alfresco.org/model/content/1.0",
              "localName" : "ownable",
              "prefixString" : "cm:ownable"
            } ]
          },
          "action" : "CREATE",
          "type" : "cm:content",
          "user" : "admin",
          "properties" : {
            "add" : {
              "{http://www.alfresco.org/model/content/1.0}isIndexed" : false,
              "{http://www.alfresco.org/model/content/1.0}created" : "2025-07-09T08:25:45.245Z",
              "{http://www.alfresco.org/model/content/1.0}isContentIndexed" : true,
              "{http://www.alfresco.org/model/content/1.0}creator" : "admin",
              "{http://www.alfresco.org/model/system/1.0}node-uuid" : "29d0c5f5-8b53-4bc7-90c5-f58b53dbc7e6",
              "{http://www.alfresco.org/model/content/1.0}name" : "page.component-1-1.user~admin~dashboard.xml",
              "{http://www.alfresco.org/model/system/1.0}store-protocol" : "workspace",
              "{http://www.alfresco.org/model/content/1.0}content" : {
                "contentUrl" : "store://2025/7/9/10/25/f58fcb51-ec31-476a-8fcb-51ec31276a61.bin",
                "mimetype" : "text/xml",
                "size" : 307,
                "encoding" : "UTF-8",
                "locale" : "en_US",
                "id" : 247,
                "infoUrl" : "contentUrl=store://2025/7/9/10/25/f58fcb51-ec31-476a-8fcb-51ec31276a61.bin|mimetype=text/xml|size=307|encoding=UTF-8|locale=en_US_"
              },
              "{http://www.alfresco.org/model/system/1.0}store-identifier" : "SpacesStore",
              "{http://www.alfresco.org/model/system/1.0}node-dbid" : 866,
              "{http://www.alfresco.org/model/system/1.0}locale" : "en_US",
              "{http://www.alfresco.org/model/content/1.0}modifier" : "admin",
              "{http://www.alfresco.org/model/content/1.0}owner" : "admin",
              "{http://www.alfresco.org/model/content/1.0}modified" : "2025-07-09T08:25:45.245Z"
            }
          }
        }
      }
    }
  }
}
